<?php

/**
 * Dev helper: replaces the most recent days with tracks that follow real roads.
 *
 *   php database/seed_road_days.php [--days=2] [--dwell=18]
 *
 * `seed.php` builds a track by interpolating a straight line between the origin
 * and each branch. Correct for stop detection, useless for road matching: the
 * points run across fields with no road under them, so OSRM answers `NoMatch`
 * and `GET /routes` returns `matched: null` for every seeded day. Nothing about
 * the road-matching feature is visible in dev as a result.
 *
 * This walks the same origin -> branch A -> branch B -> origin shape, but takes
 * each leg's geometry from a real router and samples it at the configured
 * tracking interval, so the fixes sit on streets a matcher can recognise.
 *
 * Safe to re-run; it clears the days it is about to write. Everything it
 * touches is regenerated by `php vayu migrate --fresh --seed`.
 *
 * The last day is left **open** on purpose — that is today, and today is the
 * one day `matched` is deliberately null, because a trace still being written
 * is not something the server can cache an answer about.
 */

require __DIR__ . '/../vendor/autoload.php';
Dotenv\Dotenv::createImmutable(dirname(__DIR__))->safeLoad();

require __DIR__ . '/../config/env.php';
require __DIR__ . '/../config/db.php';

foreach (['Uuid', 'Wire', 'Geo', 'Polyline', 'MapMatch', 'Envelope', 'Ctx', 'Present', 'Engine'] as $support) {
    require_once __DIR__ . "/../api/support/{$support}.php";
}

$days  = (int) (option($argv, 'days') ?? 2);
$dwell = (int) (option($argv, 'dwell') ?? 18);

$org = db_fetch_one("SELECT * FROM organizations LIMIT 1");
if (!$org) {
    exit("  no organisation — run php vayu migrate --seed first\n");
}

$timezone = new DateTimeZone($org['timezone']);
$employees = db_fetch_all("SELECT * FROM users WHERE role = 'employee' ORDER BY name");
$branches = db_fetch_all("SELECT * FROM branches ORDER BY name");

if (!$employees || !$branches) {
    exit("  no employees or branches — run php vayu migrate --seed first\n");
}

$interval = (int) db_fetch_one("SELECT location_interval_seconds FROM tracking_configs LIMIT 1")['location_interval_seconds'];

echo "\n  \033[1mRoad-following days\033[0m \033[2m{$org['timezone']} · {$interval}s interval · {$dwell}m dwell\033[0m\n";

for ($back = $days - 1; $back >= 0; $back--) {
    $date = (new DateTimeImmutable("-{$back} days", $timezone))->format('Y-m-d');
    $live = $back === 0;

    foreach ($employees as $index => $employee) {
        $count = roadDay($employee, $date, $index, $branches, $timezone, $interval, $dwell, $live);
        printf(
            "  %s  %-16s %3d fixes  %s\n",
            $date,
            substr($employee['name'], 0, 16),
            $count,
            $live ? "\033[2mopen (live — matched is null by design)\033[0m" : matchLabel($employee['id'], $date),
        );
    }
}

echo "\n";

// ---------------------------------------------------------------- internals

/**
 * One employee-day whose fixes lie on real streets.
 *
 * The shape is `seed_workday`'s — origin, two branches with a dwell at each,
 * home again — so stop detection and visit promotion see what they always saw.
 * Only the geometry between the waypoints changed.
 */
function roadDay(
    array $employee,
    string $workDate,
    int $index,
    array $branches,
    DateTimeZone $timezone,
    int $interval,
    int $dwellMinutes,
    bool $live,
): int {
    Ctx::impersonate($employee);

    // Cascade takes the fixes; stops, visits and rollups are rebuilt below.
    db_execute("DELETE FROM work_sessions WHERE employee_id = ? AND work_date = ?", [$employee['id'], $workDate]);

    $first  = $branches[$index % count($branches)];
    $second = $branches[($index + 1) % count($branches)];
    $origin = ['lat' => 23.2280 + $index * 0.006, 'lng' => 87.8500 + $index * 0.006];

    $waypoints = [
        $origin,
        ['lat' => (float) $first['lat'],  'lng' => (float) $first['lng']],
        ['lat' => (float) $second['lat'], 'lng' => (float) $second['lng']],
        $origin,
    ];

    $start = new DateTimeImmutable(
        $workDate . ' 09:' . str_pad((string) (5 + $index * 7), 2, '0', STR_PAD_LEFT) . ':00',
        $timezone,
    );

    // 40 km/h is a town two-wheeler; at a 15 s interval that is ~165 m a fix,
    // which is the spacing the matcher is tuned against.
    $spacing = 40_000 / 3600 * $interval;

    $cursor = $start;
    $fixes = [];

    for ($leg = 0; $leg < count($waypoints) - 1; $leg++) {
        $shape = roadShape($waypoints[$leg], $waypoints[$leg + 1]);

        if ($shape === null) {
            // No router, no road geometry — the straight line is still a valid
            // day, it just will not match. Better than seeding nothing.
            $shape = [
                [$waypoints[$leg]['lat'], $waypoints[$leg]['lng']],
                [$waypoints[$leg + 1]['lat'], $waypoints[$leg + 1]['lng']],
            ];
        }

        $travelled = 0.0;
        $fixes[] = fix($shape[0][0], $shape[0][1], $cursor, 8.0, 0.0);
        $cursor = $cursor->modify("+{$interval} seconds");

        for ($i = 1; $i < count($shape); $i++) {
            $travelled += Geo::distanceM($shape[$i - 1][0], $shape[$i - 1][1], $shape[$i][0], $shape[$i][1]);

            if ($travelled < $spacing) {
                continue;
            }

            $travelled = 0.0;
            $fixes[] = fix(
                $shape[$i][0] + jitter(10),
                $shape[$i][1] + jitter(10),
                $cursor,
                mt_rand(5, 18),
                36 + mt_rand(0, 8),
            );
            $cursor = $cursor->modify("+{$interval} seconds");
        }

        // The dwell — a parked phone repeating one point, which is exactly what
        // stop detection is written against. Skipped on the last leg: arriving
        // home ends the day rather than starting another stop.
        if ($leg === count($waypoints) - 2) {
            continue;
        }

        $steps = (int) round($dwellMinutes * 60 / $interval);
        $to = $waypoints[$leg + 1];

        for ($s = 0; $s < $steps; $s++) {
            // A few metres of drift, which is what a parked handset with a good
            // fix actually produces. The original seeder used ~13 m steps —
            // above the matcher's thinning threshold, so every one of them
            // survived and a dwell ate the whole per-request budget.
            $fixes[] = fix(
                $to['lat'] + jitter(3),
                $to['lng'] + jitter(3),
                $cursor,
                9 + ($s % 4),
                0.0,
            );
            $cursor = $cursor->modify("+{$interval} seconds");
        }
    }

    $sessionId = Uuid::v4();

    db_execute(
        "INSERT INTO work_sessions (id, employee_id, client_id, work_date, seq, started_at, start_lat, start_lng)
         VALUES (?, ?, ?, ?, 1, ?, ?, ?)",
        [
            $sessionId, $employee['id'], Uuid::v4(), $workDate,
            $fixes[0]['recordedAt'], $fixes[0]['latitude'], $fixes[0]['longitude'],
        ],
    );

    $session = db_fetch_one("SELECT * FROM work_sessions WHERE id = ?", [$sessionId]);

    // Through the real ingest path, so these obey the same accuracy and jump
    // rules as a live upload and derive the same stops.
    Engine::ingest($session, $fixes);

    if (!$live) {
        $endedAt = $fixes[count($fixes) - 1]['recordedAt'];

        db_execute("UPDATE work_sessions SET ended_at = ? WHERE id = ?", [$endedAt, $sessionId]);
        db_execute("UPDATE stop_records SET departure = ? WHERE session_id = ? AND departure IS NULL", [$endedAt, $sessionId]);
        db_execute(
            "UPDATE company_visits SET departure = ?, status = 'completed' WHERE session_id = ? AND departure IS NULL",
            [$endedAt, $sessionId],
        );
        Engine::recompute($employee['id'], $workDate);
    }

    return count($fixes);
}

/**
 * Road geometry between two points, as `[lat, lng]` vertices.
 *
 * A directions call is the right tool *here* and the wrong one in MapMatch: the
 * question is "what would a rider have ridden", not "what explains these
 * fixes". Returns null on any failure — the caller falls back to a straight
 * line rather than seeding an empty day.
 */
function roadShape(array $from, array $to): ?array
{
    static $client = null;
    $client ??= stream_context_create(['http' => [
        'header'        => 'User-Agent: hazra-ev/1.0 (dev seeder)',
        'timeout'       => 20,
        'ignore_errors' => true,
    ]]);

    $base = rtrim((string) env('MATCH_BASE_URL', 'https://router.project-osrm.org'), '/');
    $url = sprintf(
        '%s/route/v1/driving/%f,%f;%f,%f?overview=full&geometries=polyline6',
        $base, $from['lng'], $from['lat'], $to['lng'], $to['lat'],
    );

    $body = @file_get_contents($url, false, $client);
    if ($body === false) {
        return null;
    }

    $decoded = json_decode($body, true);
    if (!is_array($decoded) || ($decoded['code'] ?? '') !== 'Ok') {
        return null;
    }

    // Courtesy pause: this is a shared demo host with no SLA.
    usleep(300_000);

    $shape = Polyline::decode($decoded['routes'][0]['geometry']);

    return count($shape) < 2 ? null : $shape;
}

function fix(float $lat, float $lng, DateTimeImmutable $at, float $accuracy, float $speed): array
{
    return [
        'id'         => Uuid::v4(),
        'latitude'   => $lat,
        'longitude'  => $lng,
        'accuracy'   => $accuracy,
        'speedKmh'   => $speed,
        'recordedAt' => $at->setTimezone(new DateTimeZone('UTC'))->format(Wire::TS),
    ];
}

/** Metres of horizontal error, expressed as degrees. */
function jitter(float $metres): float
{
    return ($metres / 111_320.0) * ((mt_rand(0, 2000) / 1000.0) - 1.0);
}

function matchLabel(string $employeeId, string $workDate): string
{
    $matched = MapMatch::forDay($employeeId, $workDate, true);

    if ($matched === null) {
        return "\033[31munmatched\033[0m";
    }

    return sprintf(
        "\033[32m%s\033[0m \033[2m%.2f km · conf %.2f\033[0m",
        $matched['status'], $matched['distanceKm'], $matched['confidence'],
    );
}

function option(array $argv, string $name): ?string
{
    foreach ($argv as $arg) {
        if (str_starts_with($arg, "--{$name}=")) {
            return substr($arg, strlen($name) + 3);
        }
    }

    return null;
}
